version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./webServer
    volumes:
      - ./webServer:/app
      - ./logs/web:/app/python_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/users
      TZ: Europe/Moscow
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    environment:
      TZ: Europe/Moscow
    depends_on:
      - web
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: alerts_db
      CLICKHOUSE_USER: alerts_user
      CLICKHOUSE_PASSWORD: alerts_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  alertsystem:
    build: ./alertsystem
    volumes:
      - ./logs/nginx:/logs/nginx
    depends_on:
      - web
      - clickhouse
    environment:
      TZ: Europe/Moscow

  notifier:
    build: ./notifier
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      CLICKHOUSE_DSN: clickhouse://alerts_user:alerts_password@clickhouse:9000/alerts_db
    depends_on:
      - clickhouse

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    depends_on:
      - clickhouse
  
volumes:
  postgres_data:
  clickhouse_data:
  grafana_data:
