apiVersion: 1
datasources:
  - name: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      defaultDatabase: alerts_db
      username: alerts_user
      protocol: http
    secureJsonData:
      password: alerts_password
